title: "Dilan Wijesinghe"
email: dilanwijesinghe2023@u.northwestern.edu
timezone: CST
baseurl: "/dilan-wijesinghe"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Dilan Wijesinghe
paginate: 30
disqus: 'portfolio'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  Dilan:
    name: Dilan Wijesinghe
    display_name: Dilan
    avatar: ''
    email: dilanwijesinghe2023@u.northwestern.edu
    description: "Default Description"

# Social
social:
  instagram: 

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives